/**
 * Mock AFRC Contract Data
 * Realistic sample data for instant prototyping
 */

import { Award } from '../types';

export const MOCK_AWARDS: Award[] = [
  // Boeing
  {
    id: 1,
    generated_internal_id: 'award_1',
    award_id: 'fa1234567890001',
    description: 'Aircraft structural components and assemblies',
    award_type: 'B',
    award_type_code: 'B',
    recipient_id: 'rec_001',
    recipient_name: 'Boeing Defense, Space & Security',
    recipient_unique_id: '123456789',
    recipient_dba_name: null,
    action_date: '2024-03-15',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 125000000,
    potential_total_value_of_award: 250000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '336411',
    naics_description: 'Aircraft Parts and Auxiliary Equipment Manufacturing',
    psc_code: '1680',
    psc_description: 'Aircraft Structure Components',
    prime_award_base_transaction_id: 'base_001',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_1',
  },
  // Lockheed Martin
  {
    id: 2,
    generated_internal_id: 'award_2',
    award_id: 'fa1234567890002',
    description: 'Avionics systems and electronic warfare equipment',
    award_type: 'A',
    award_type_code: 'A',
    recipient_id: 'rec_002',
    recipient_name: 'Lockheed Martin Corporation',
    recipient_unique_id: '987654321',
    recipient_dba_name: null,
    action_date: '2024-04-10',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 95000000,
    potential_total_value_of_award: 380000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '334511',
    naics_description: 'Search, Detection, Navigation, Guidance, Aeronautical Systems',
    psc_code: '1250',
    psc_description: 'Radar Systems and Equipment',
    prime_award_base_transaction_id: 'base_002',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_2',
  },
  // General Electric
  {
    id: 3,
    generated_internal_id: 'award_3',
    award_id: 'fa1234567890003',
    description: 'Jet engine maintenance and overhaul services',
    award_type: 'D',
    award_type_code: 'D',
    recipient_id: 'rec_003',
    recipient_name: 'General Electric Aviation',
    recipient_unique_id: '555666777',
    recipient_dba_name: null,
    action_date: '2024-05-20',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 45000000,
    potential_total_value_of_award: 180000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '811310',
    naics_description: 'Commercial and Industrial Machinery and Equipment Repair',
    psc_code: '1630',
    psc_description: 'Engine Accessories',
    prime_award_base_transaction_id: 'base_003',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_3',
  },
  // Raytheon
  {
    id: 4,
    generated_internal_id: 'award_4',
    award_id: 'fa1234567890004',
    description: 'Missile systems and defensive counter-measures',
    award_type: 'B',
    award_type_code: 'B',
    recipient_id: 'rec_004',
    recipient_name: 'Raytheon Missiles & Defense',
    recipient_unique_id: '888999000',
    recipient_dba_name: null,
    action_date: '2024-06-01',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 78000000,
    potential_total_value_of_award: 312000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '336414',
    naics_description: 'Guided Missile and Space Vehicle Manufacturing',
    psc_code: '1255',
    psc_description: 'Missile Systems',
    prime_award_base_transaction_id: 'base_004',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_4',
  },
  // Northrop Grumman
  {
    id: 5,
    generated_internal_id: 'award_5',
    award_id: 'fa1234567890005',
    description: 'Command and control systems integration',
    award_type: 'A',
    award_type_code: 'A',
    recipient_id: 'rec_005',
    recipient_name: 'Northrop Grumman Systems Corporation',
    recipient_unique_id: '111222333',
    recipient_dba_name: null,
    action_date: '2024-02-14',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 52000000,
    potential_total_value_of_award: 208000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '541512',
    naics_description: 'Computer Systems Design and Related Services',
    psc_code: '7030',
    psc_description: 'Data Processing and Telecommunications',
    prime_award_base_transaction_id: 'base_005',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_5',
  },
  // Harris Corporation
  {
    id: 6,
    generated_internal_id: 'award_6',
    award_id: 'fa1234567890006',
    description: 'Communications and networking equipment',
    award_type: 'C',
    award_type_code: 'C',
    recipient_id: 'rec_006',
    recipient_name: 'Harris Corporation',
    recipient_unique_id: '444555666',
    recipient_dba_name: null,
    action_date: '2024-01-25',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 28000000,
    potential_total_value_of_award: 112000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '334220',
    naics_description: 'Radio and Television Broadcasting and Wireless',
    psc_code: '5865',
    psc_description: 'Communications Equipment',
    prime_award_base_transaction_id: 'base_006',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_6',
  },
  // Collins Aerospace
  {
    id: 7,
    generated_internal_id: 'award_7',
    award_id: 'fa1234567890007',
    description: 'Hydraulic systems and components',
    award_type: 'B',
    award_type_code: 'B',
    recipient_id: 'rec_007',
    recipient_name: 'Collins Aerospace',
    recipient_unique_id: '777888999',
    recipient_dba_name: null,
    action_date: '2024-03-30',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 35000000,
    potential_total_value_of_award: 140000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '336412',
    naics_description: 'Aircraft Engine and Engine Parts Manufacturing',
    psc_code: '1625',
    psc_description: 'Fluid Power Components',
    prime_award_base_transaction_id: 'base_007',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id': 'award_7',
  },
  // Huntington Ingalls
  {
    id: 8,
    generated_internal_id: 'award_8',
    award_id: 'fa1234567890008',
    description: 'Engineering and design services',
    award_type: 'A',
    award_type_code: 'A',
    recipient_id: 'rec_008',
    recipient_name: 'Huntington Ingalls Industries',
    recipient_unique_id: '222333444',
    recipient_dba_name: null,
    action_date: '2024-04-15',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 42000000,
    potential_total_value_of_award: 168000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '541330',
    naics_description: 'Engineering Services',
    psc_code: '7110',
    psc_description: 'Technical Services',
    prime_award_base_transaction_id: 'base_008',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_8',
  },
  // Textron
  {
    id: 9,
    generated_internal_id: 'award_9',
    award_id: 'fa1234567890009',
    description: 'Aircraft training and simulation systems',
    award_type: 'D',
    award_type_code: 'D',
    recipient_id: 'rec_009',
    recipient_name: 'Textron Defense & Aerospace',
    recipient_unique_id: '666777888',
    recipient_dba_name: null,
    action_date: '2024-05-10',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 31000000,
    potential_total_value_of_award: 124000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '611310',
    naics_description: 'Technical and Trade Schools',
    psc_code: '7500',
    psc_description: 'Training and Simulation Systems',
    prime_award_base_transaction_id: 'base_009',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_9',
  },
  // L-3 Technologies
  {
    id: 10,
    generated_internal_id: 'award_10',
    award_id: 'fa1234567890010',
    description: 'Electronic warfare and intelligence systems',
    award_type: 'B',
    award_type_code: 'B',
    recipient_id: 'rec_010',
    recipient_name: 'L3 Harris Technologies',
    recipient_unique_id: '999000111',
    recipient_dba_name: null,
    action_date: '2024-06-15',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 88000000,
    potential_total_value_of_award: 352000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '334511',
    naics_description: 'Search, Detection, Navigation, Guidance, Aeronautical Systems',
    psc_code: '6610',
    psc_description: 'Electronic Warfare Systems',
    prime_award_base_transaction_id: 'base_010',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_10',
  },
  // Additional contractors
  {
    id: 11,
    generated_internal_id: 'award_11',
    award_id: 'fa1234567890011',
    description: 'Logistics and supply chain management',
    award_type: 'A',
    award_type_code: 'A',
    recipient_id: 'rec_011',
    recipient_name: 'DynCorp International',
    recipient_unique_id: '333444555',
    recipient_dba_name: null,
    action_date: '2024-02-28',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 18000000,
    potential_total_value_of_award: 72000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '561210',
    naics_description: 'Facilities Support Services',
    psc_code: '7010',
    psc_description: 'Logistics and Supply Chain Services',
    prime_award_base_transaction_id: 'base_011',
    business_types: ['Large Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_11',
  },
  // More small business examples
  {
    id: 12,
    generated_internal_id: 'award_12',
    award_id: 'fa1234567890012',
    description: 'Specialized testing and inspection services',
    award_type: 'C',
    award_type_code: 'C',
    recipient_id: 'rec_012',
    recipient_name: 'Phoenix International Inc',
    recipient_unique_id: '121314151',
    recipient_dba_name: null,
    action_date: '2024-03-05',
    action_type: 'New Award',
    action_type_code: 'NEW',
    federal_action_obligation: 8500000,
    potential_total_value_of_award: 34000000,
    funding_agency_id: '057',
    funding_agency_name: 'Department of the Air Force',
    naics_code: '541380',
    naics_description: 'Testing Laboratories',
    psc_code: '9310',
    psc_description: 'Quality Assurance and Testing',
    prime_award_base_transaction_id: 'base_012',
    business_types: ['Small Business', 'For-Profit Organization'],
    generated_unique_award_id: 'award_12',
  },
];

export function getMockAwards(): Award[] {
  return MOCK_AWARDS;
}
